# docker-compose.yml

services:
  mysql:
    image: mysql:8.0
    container_name: taskmanager_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-db_taskmanager}
      MYSQL_USER: ${DB_USERNAME:-taskmanager}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - '${DB_PORT:-3307}:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - taskmanager_network

volumes:
  mysql:
    driver: local

networks:
  taskmanager_network:
    driver: bridge
